name: Build-Typespec CI

on:
  push:
    paths:
      - 'main.tsp'
  workflow_dispatch:

env:
    ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
    REPO_NAME: "Typespec-poc"
    
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 17

      - name: Install @typespec/compiler
        run: npm install -g @typespec/compiler

      - name: Install dependencies
        run: tsp install

      - name: Compile TypeScript
        run: tsp compile .
        
      - name: Commit and Push changes
        run: |
          git config user.name mismaeel
          git config user.email github-actions@gmail.com
          git add tsp-output/@typespec/openapi3/openapi.yaml
          # git add --all
          git commit -m "generated"
          git push --force
        
  #    - name: Push changes to client branch
   #     uses: ad-m/github-push-action@master
    #    with:
     #      github_token: ${{ secrets.ACCESS_TOKEN }}
      #     force: True
          
