
name: Build Kiota

on:
 workflow_dispatch:
jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 7.0.x
    - name: Install Kiota tool
      run: dotnet tool install --global Microsoft.OpenApi.Kiota
      
    - name: Generate API SDK
      run: kiota generate -openapi tsp-output\@typespec\openapi3\openapi.yaml --language csharp --output "kiota-output\client-sdk\.Net"
      
    - name: Commit and Push changes
      run: |
         git config user.name github-actions
         git config user.email github-actions@github.com
         git add kiota-output/client-sdk/.Net
         # git add --all
         git commit -m "generated"
         git push
        
 
